version: '3'

services:
  crafty:
    container_name: crafty_container
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    restart: always
    environment:
        - TZ=Europe/Madrid
    ports:
        - "8001:8000" # HTTP (in my case 8000 used by portainer)
        - "8443:8443" # HTTPS
        - "8123:8123" # DYNMAP
        - "19132:19132/udp" # BEDROCK
        - "25500-25600:25500-25600" # MC SERV PORT RANGE
    volumes:
        - ./crafty/backups:/crafty/backups
        - ./crafty:/crafty/logs
        - ./crafty/servers:/crafty/servers
        - ./crafty/config:/crafty/app/config
        - ./crafty/import:/crafty/import
