# warning: Homebridge does not work when running in Docker
# for Mac or Docker for Windows
# https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Docker
version: '3'
services:
  homebridge:
    image: oznu/homebridge:ubuntu
    container_name: homebridge
    restart: always
    network_mode: host
    environment:
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
    volumes:
      - homebridge:/homebridge
volumes:
  homebridge: